apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwardenrs
spec:
  releaseName: bitwardenrs
  chart:
    spec:
      chart: bitwardenrs
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "2.0.2"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    bitwardenrs:
      domain: "bw.asicforecast.com"
      
    ingress:
      enabled: true
      hosts:
        - bw.asicforecast.com
      annotations:
        kubernetes.io/ingress.class: traefik
      path: "/"
    service:
      type: NodePort
