---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-gitops
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/KyleCulp/k8s-gitops

