---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  # dependsOn:
  #   - name: cert-manager
  #     namespace: cert-manager
  chart:
    spec:
      chart: traefik
      # renovate: registryUrl=https://helm.traefik.io/traefik
      version: 9.14.2
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    providers:
      kubernetesCRD:
        enabled: true
        namespaces: ["services", "media", "devops", "traefik"]
    additionalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--certificatesresolvers.cloudflare.acme.email=me@kyleculp.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
      - "--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesResolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
    env:
      - name: TZ
        value: America/Chicago
    ingressClass:
      enabled: true
    isDefaultClass: "true"
    ingressRoute:
      dashboard:
        enabled: true
    # persistence:
    #   enabled: true
    #   existingClaim: "traefik-cert-pvc"
    #   path: "/data"
    service:
      enabled: true
    ports:
      ssh:
        port: 2222
        expose: true
        exposedPort: 22
        protocol: TCP
      traefik:
        port: 9000
        expose: true
        exposedPort: 9000
        protocol: TCP
      web:
        port: 8000
        expose: true
        exposedPort: 80
        protocol: TCP
        redirectTo: websecure
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
          certResolver: cloudflare
          domains:
            - kyleculp: kyleculp.com
              sans:
                - traefik.kyleculp.com
                - git.kyleculp.com
            - asicforecast: asicforecast.com
              sans:
                - bw.asicforecast.com
                - traefik.asicforecast.com
    logs:
      general:
        level: INFO
      access:
        enabled: true
  interval: 5m0s
