---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio-operator
      version: 4.0.3
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    operator:
    tenants:
      # - name: backups
      #   image:
      #     repository: minio/minio
      #     tag: RELEASE.2021-03-01T04-20-55Z
      #     pullPolicy: IfNotPresent
      #   secrets:
      #     name: minio1-secret
      #     accessKey: ThisIsAVeryLongPasswordForExample
      #     secretKey: ThisIsAVeryLongPasswordForExample
      #   metrics:
      #     enabled: false
      #     port: 9000
      #   pools:
      #     - servers: 4
      #       ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      #       volumesPerServer: 4
      #       ## size specifies the capacity per volume
      #       size: 10Gi
      #       ## storageClass specifies the storage class name to be used for this pool
      #       storageClassName: local-path
      #   console:
      #     image:
      #       repository: minio/console
      #       tag: v0.6.3
      #       pullPolicy: IfNotPresent
      #     replicaCount: 1
      #     secrets:
      #       name: console-secret
      #       passphrase: ThisIsAVeryLongPasswordForExample
      #       salt: ThisIsAVeryLongPasswordForExample
      #       accessKey: ThisIsAVeryLongPasswordForExample
      #       secretKey: ThisIsAVeryLongPasswordForExample
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio-operator-ingress
  namespace: minio
spec:
  routes:
    - kind: Rule
      match: Host(`minio.asicforecast.com`)
      services:
        - kind: Service
          name: minio
          namespace: minio
          passHostHeader: true
          weight: 10
          port: 80
  tls:
    secretName: asicforecast-tls
