---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 4.0.3
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio-routes
  namespace: minio
spec:
  routes:
    - kind: Rule
      match: Host(`minio.asicforecast.com`)
      services: 
      - kind: Service
        name: minio
        namespace: minio
        passHostHeader: true
        weight: 10
        port: 80
      - kind: Service
        name: minio
        namespace: minio
        passHostHeader: true
        weight: 10
        port: 443
  tls:
    secretName: asicforecast-tls