---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio-operator
      version: ">=4.0.2 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 1m
  values:
    operator:
      clusterDomain: minio.asicforecast.com
    tenants:
    console:
      replicaCount: 1
---
  apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRoute
  metadata:
    name: minio-console
    namespace: minio
  spec:
    routes:
      - kind: Rule
        match: Host(`minio.asicforecast.com`)
        services:
          - kind: Service
            name: minio-console
            namespace: minio
            passHostHeader: true
            weight: 10
            port: 9090
    tls:
      secretName: asicforecast-tls
