---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio-operator
      version: ">=4.0.2 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 1m
  values:
    operator:
      clusterDomain: minio.asicforecast.com
    pools:
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
      - servers: 4
        ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
        volumesPerServer: 4
        ## size specifies the capacity per volume
        size: 10Gi
        ## storageClass specifies the storage class name to be used for this pool
        storageClassName: local-path
    console:
      replicaCount: 1
---
  apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRoute
  metadata:
    name: minio-console
    namespace: minio
  spec:
    routes:
      - kind: Rule
        match: Host(`minio.asicforecast.com`)
        services:
          - kind: Service
            name: minio-console
            namespace: minio
            passHostHeader: true
            weight: 10
            port: 9090
    tls:
      secretName: asicforecast-tls
