# https://github.com/zbigniewzolnierowicz/k8s-home/blob/main/cluster/default/traefik/CustomResourceDefinition.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: traefik-crd
  namespace: traefik
spec:
  interval: 5m
  url: https://github.com/traefik/traefik-helm-chart/
  ignore: |
    /*
    !/traefik/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-routes-kustomize
  namespace: traefik
spec:
  dependsOn:
    - name: traefik-crd
      namespace: default
  interval: 5m
  path: "./kustomization.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: traefik-crd