---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-cert-pvc
  namespace: traefik
spec:
  storageClassName: openebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi