apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - release.yaml
  # - volume.yaml
  # - dashboard.yaml
  - whoami.yaml
  - whoami-route.yaml
