---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-hostpath-traefik-certs-pvc
  namespace: traefik
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi