---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gemini 
  namespace: gemini
spec:
  interval: 5m
  chart:
    spec:
      chart: gemini 
      version: 0.0.4
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system