version: '3'
services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/inginx.conf
      # - ./ssl:/etc/nginx/ssl:ro
      # - ./snippets:/etc/nginx/snippets:ro
      # - ./protect:/etc/nginx/protect:ro
