version: "3.7"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
      - "8443:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/etc/nginx/logs
      - ./nginx/certs:/etc/nginx/certs
    # networks:
    #   homelab:
    #     ipv4_address: 172.20.0.4

  # In the future, this will be moved off this vm but not into k8s
  miniobackups:
    image: 'docker.io/bitnami/minio:2021-debian-10'
    container_name: miniobackups
    restart: always
    env_file:
     - ../priv/minio.env
    volumes: 
      - minio:/data


volumes:
  minio:
