version: '3'
services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "8443:443"
      - "8442:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      # - ./ssl:/etc/nginx/ssl:ro
      # - ./snippets:/etc/nginx/snippets:ro
      # - ./protect:/etc/nginx/protect:ro
    networks:
      - proxy-tier