---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  # dependsOn:
  #   - name: cert-manager
  #     namespace: cert-manager
  chart:
    spec:
      chart: sealed-secrets
      # renovate: registryUrl=https://helm.traefik.io/traefik
      version: 1.15.0-r2
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  values:

  interval: 5m0s
