---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  chart:
    spec:
      chart: openebs
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    
  interval: 10m0s