---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwarden
  namespace: services
spec:
  interval: 1m
  chart:
    spec:
      chart: bitwardenrs
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "2.0.2"
  values:
    env:
      - name: TZ
        value: America/Chicago
    bitwardenrs:
      domain: "bitwarden.kyleculp.com"
      signupsAllowed: true
    persistence:
      enabled: true
      size: 1Gi
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bitwarden
  namespace: services
spec:
  routes:
    - kind: Rule
      match: Host(`bitwarden.kyleculp.com`)
      services:
        - kind: Service
          name: bitwarden
          namespace: services
          passHostHeader: true
          weight: 10
          port: 80
  tls:
    secretName: kyleculp-tls
