---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoami
  namespace: services
spec:
  # dependsOn:
  #   - name: cert-manager
  #     namespace: cert-manager
  chart:
    spec:
      chart: sealed-secrets
      # renovate: registryUrl=https://helm.traefik.io/traefik
      version: 1.15.0-r2
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  values:

  interval: 5m0s
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: services
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`whoami.asicforecast.com`)
      kind: Rule
      services:
        - name: whoami
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-tls
  namespace: services
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whoami.asicforecast.com`) && PathPrefix(`/tls`)
      services:
        - name: whoami
          port: 80
  tls:
    certResolver: cloudflare