---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: services
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`whoami.asicforecast.com`)
      kind: Rule
      services:
        - name: whoami
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-tls
  namespace: services
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whoami.asicforecast.com`) && PathPrefix(`/tls`)
      services:
        - name: whoami
          port: 443
  tls:
    certResolver: cloudflare