apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - repos/bitnami.yaml
  - repos/k8s-at-home.yaml
  - repos/openebs.yaml
  - repos/jetstack.yaml
  