---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: flux-system
  chart:
    spec:
      chart: cert-manager
      # renovate: registryUrl=https://charts.jetstack.io/
      version: v1.1.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 5m
  values:
    installCRDs: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
      - --dns01-recursive-nameservers-only