---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gloo
  namespace: gloo-system
spec:
  # dependsOn:
  #   - name: cert-manager
  #     namespace: cert-manager
  interval: 5m
  chart:
    spec:
      chart: gloo
      # renovate: registryUrl=https://helm.traefik.io/traefik
      version: 1.6.17
      sourceRef:
        kind: HelmRepository
        name: gloo
        namespace: flux-system
  values:
    gateway:
      enabled: false
    ingress:
      enabled: true